##挑戰題一：Bubble Sort

In [ ]:
def tidy(x):
  print("開始整理：",x)
  a = int(x[0])
  for j in range(len(x)-1):
    print("\n正在檢查前",j+2,"個數的順序")
    while x[j+1] <= x[j]:
      print("交換",x[j+1],"和",x[j])
      a = x[j]
      x[j] = x[j+1]
      x[j+1] = a
      if j > 0:
        j = j-1
      print(x)
  print("\n整理完成：",x)

x = np.random.randint(1,100,5)
tidy(x)

開始整理： [99 17 34 65 44]

正在檢查前 2 個數的順序
交換 17 和 99
[17 99 34 65 44]

正在檢查前 3 個數的順序
交換 34 和 99
[17 34 99 65 44]

正在檢查前 4 個數的順序
交換 65 和 99
[17 34 65 99 44]

正在檢查前 5 個數的順序
交換 44 和 99
[17 34 65 44 99]
交換 44 和 65
[17 34 44 65 99]

整理完成： [17 34 44 65 99]


##第二題：算閏年

In [ ]:
%matplotlib inline

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
def leap(x):
  if (x%4==0):
    if (x%100==0):
      if (x%400==0):
        print(x,"是閏年")
      else:
        print(x,"不是閏年")
    else:
      print(x,"是閏年")
  else:
    print(x,"不是閏年")

year = input("請輸入一個西元年份")
leap(int(year))

請輸入一個西元年份2000
2000 是閏年


##第三題：矩陣加法、乘法

In [ ]:
# 創建兩個5*5矩陣
matrix1 = np.random.randint(1,100,(5,5))
matrix2 = np.random.randint(1,100,(5,5))

# 矩陣相加
print(matrix1 + matrix2)
# 矩陣相乘
print(np.dot(matrix1, matrix2))

[[ 91 132  60 126 118]
 [134 134 127 103 117]
 [ 73  32  97 102 129]
 [ 70 101  22  42  55]
 [ 95  71 135 140 102]]
[[11837 15529  9403 20202 11157]
 [14537 15722 11130 26688 15247]
 [12583  8048  8684 16470  5781]
 [ 4770  4131  2989  7013  4647]
 [17590 11236  9120 19489  8783]]


##第四題：錄取分數表格

In [ ]:
# 儲存需要的資料
sub=["國文", "英文", "數甲", "數乙", "物理", "化學", "生物", "歷史", "地理", "公民"]
weight={
"土語系": [2, 2, 0, 1, 0, 0, 0, 1, 1, 0],
"財政系": [1, 1.5, 0, 1.5, 0, 0, 0, 0, 0, 0],
"金融系": [1, 1.5, 0, 2, 0, 0, 0, 0, 0, 0],
"國貿系": [1.5, 2, 0, 2, 0, 0, 0, 0, 0, 0],
"會計系": [1.5, 2, 0, 2, 0, 0, 0, 1, 1, 0],
"法律系": [1, 2, 0, 1, 0, 0, 0, 1, 0, 1],
"公行系": [1, 1.5, 0, 1.25, 0, 0, 0, 0, 0, 1.25],
"應數系": [1, 1, 1.5, 0, 1, 1, 0, 0, 0, 0],
"教育系": [1.5, 2, 0, 1.25, 0, 0, 0, 1, 1, 0]
}
score=[86.5, 79.4, 88.2, 96.5, 86.3, 76.8, 96.1, 78.5, 82.4, 88.6]

#儲存index和column的值
department=[]
W=[]
for i in weight:
  department.append(i)
  W.append(weight[i])
df = pd.DataFrame(W,index=department, columns=sub)

#也可以直接轉置
# df = pd.DataFrame(weight,sub)
# dft = df.T

# 在df新增一列紀錄加權成績
df["加權分數"] = np.dot(df,score)
df

國文   英文   數甲    數乙  物理  化學  生物  歷史  地理    公民     加權分數
土語系  2.0  2.0  0.0  1.00   0   0   0   1   1  0.00  589.200
財政系  1.0  1.5  0.0  1.50   0   0   0   0   0  0.00  350.350
金融系  1.0  1.5  0.0  2.00   0   0   0   0   0  0.00  398.600
國貿系  1.5  2.0  0.0  2.00   0   0   0   0   0  0.00  481.550
會計系  1.5  2.0  0.0  2.00   0   0   0   1   1  0.00  642.450
法律系  1.0  2.0  0.0  1.00   0   0   0   1   0  1.00  508.900
公行系  1.0  1.5  0.0  1.25   0   0   0   0   0  1.25  436.975
應數系  1.0  1.0  1.5  0.00   1   1   0   0   0  0.00  461.300
教育系  1.5  2.0  0.0  1.25   0   0   0   1   1  0.00  570.075